;;; Generated by Verrazano 0.5
;;; WARNING: This is a {NOt fully} generated file, editing it is {not such} unwise! 


(cl:in-package :cl-user)

(cl:defpackage :graphviz-cffi-bindings
  (:use :cffi)
  (:nicknames)
  (:export "JUST"
           "YOFFSET-CENTERLINE"
           "YOFFSET-LAYOUT"
           "FONT"
           "FREE-LAYOUT"
           "LAYOUT"
           "STR"
           "TEXTPARA-T"
           "CNT"
           "COLOR"
           "HTMLFONT-T"
           "POSTSCRIPT-ALIAS"
           "SVG-FONT-STYLE"
           "SVG-FONT-WEIGHT"
           "SVG-FONT-FAMILY"
           "XFIG-CODE"
           "STYLE"
           "STRETCH"
           "FAMILY"
           "ELIST-NEW"
           "ELIST-CONSTRUCTOR"
           "ELIST-OPERATOR-="
           "SHAPE-FUNCTIONS-NEW"
           "SHAPE-FUNCTIONS-CONSTRUCTOR"
           "SHAPE-FUNCTIONS-OPERATOR-="
           "BOX-OPERATOR-="
           "AGRAPHINFO-T-NEW"
           "AGRAPHINFO-T-CONSTRUCTOR"
           "AGRAPHINFO-T-OPERATOR-="
           "TEXTLABEL-T-NEW"
           "TEXTLABEL-T-CONSTRUCTOR"
           "TEXTLABEL-T-OPERATOR-="
           "NODEQUEUE-NEW"
           "NODEQUEUE-CONSTRUCTOR"
           "NODEQUEUE-OPERATOR-="
           "AGEDGE-T-NEW"
           "AGEDGE-T-CONSTRUCTOR"
           "AGEDGE-T-OPERATOR-="
           "AGNODE-T-NEW"
           "AGNODE-T-CONSTRUCTOR"
           "AGNODE-T-OPERATOR-="
           "SHAPE-DESC-NEW"
           "SHAPE-DESC-CONSTRUCTOR"
           "SHAPE-DESC-OPERATOR-="
           "RANK-T-NEW"
           "RANK-T-CONSTRUCTOR"
           "RANK-T-OPERATOR-="
           "AGNODEINFO-T-NEW"
           "AGNODEINFO-T-CONSTRUCTOR"
           "AGNODEINFO-T-OPERATOR-="
           "SHAPE-T-NEW"
           "SHAPE-T-CONSTRUCTOR"
           "SHAPE-T-OPERATOR-="
           "POINTF-S-NEW"
           "POINTF-S-CONSTRUCTOR"
           "POINTF-S-OPERATOR-="
           "SPLINES-NEW"
           "SPLINES-CONSTRUCTOR"
           "SPLINES-OPERATOR-="
           "STROKE-T-NEW"
           "STROKE-T-CONSTRUCTOR"
           "STROKE-T-OPERATOR-="
           "SPLINE-INFO-OPERATOR-="
           "BEZIER-NEW"
           "BEZIER-CONSTRUCTOR"
           "BEZIER-OPERATOR-="
           "GVLAYOUT-FEATURES-T-OPERATOR-="
           "AGDATA-T-NEW"
           "AGDATA-T-CONSTRUCTOR"
           "AGDATA-T-OPERATOR-="
           "AGPROTO-T-NEW"
           "AGPROTO-T-CONSTRUCTOR"
           "AGPROTO-T-OPERATOR-="
           "FIELD-T-NEW"
           "FIELD-T-CONSTRUCTOR"
           "FIELD-T-OPERATOR-="
           "PATH-NEW"
           "PATH-CONSTRUCTOR"
           "PATH-OPERATOR-="
           "AGRAPH-T-NEW"
           "AGRAPH-T-CONSTRUCTOR"
           "AGRAPH-T-OPERATOR-="
           "FDP-PARMS-T-OPERATOR-="
           "AGDICT-T-NEW"
           "AGDICT-T-CONSTRUCTOR"
           "AGDICT-T-OPERATOR-="
           "LAYOUT-T-NEW"
           "LAYOUT-T-CONSTRUCTOR"
           "LAYOUT-T-OPERATOR-="
           "POINT-OPERATOR-="
           "ADJMATRIX-T-NEW"
           "ADJMATRIX-T-CONSTRUCTOR"
           "ADJMATRIX-T-OPERATOR-="
           "PATHEND-T-NEW"
           "PATHEND-T-CONSTRUCTOR"
           "PATHEND-T-OPERATOR-="
           "BOXF-OPERATOR-="
           "PORT-NEW"
           "PORT-CONSTRUCTOR"
           "PORT-OPERATOR-="
           "NLIST-T-NEW"
           "NLIST-T-CONSTRUCTOR"
           "NLIST-T-OPERATOR-="
           "AGEDGEINFO-T-NEW"
           "AGEDGEINFO-T-CONSTRUCTOR"
           "AGEDGEINFO-T-OPERATOR-="
           "POLYGON-T-NEW"
           "POLYGON-T-CONSTRUCTOR"
           "POLYGON-T-OPERATOR-="
           "AGSYM-T-NEW"
           "AGSYM-T-CONSTRUCTOR"
           "AGSYM-T-OPERATOR-="
           "GV-CONTEXT"
           "GV-PLUGINS-GRAPH"
           "AGLSTNODE"
           "AGPUTC"
           "AGSTRCANON"
           "AGSUBG"
           "GV-NEXT-INPUT-GRAPH"
           "GV-ADD-LIBRARY"
           "APIS"
           "PACKAGENAME"
           "GVPLUGIN-LIBRARY-T"
           "TYPES"
           "API"
           "GVPLUGIN-API-T"
           "FEATURES"
           "ENGINE"
           "QUALITY"
           "GVPLUGIN-INSTALLED-T"
           "API-LOADIMAGE"
           "API-DEVICE"
           "API-TEXTLAYOUT"
           "API-LAYOUT"
           "API-RENDER"
           "API-T"
           "AGXGET"
           "AGSETERR"
           "BOX"
           "AGREAD-USERGETS"
           "AGHTMLSTR"
           "GV-FINALIZE"
           "AGFINDNODE"
           "QSORT-CMPF"
           "AGFSTNODE"
           "AGPROTOGRAPH"
           "GV-RENDER-FILENAME"
           "AGSTRDUP"
           "AGGET"
           "AGPUTS"
           "AGSTRFREE"
           "AGSET"
           "GV-LAYOUT-JOBS"
           "S"
           "A"
           "AGNXTOUT"
           "LIMIT"
           "STORE"
           "NODEQUEUE"
           "AGCANONICAL"
           "GVC-VERSION"
           "GVC-BUILD-DATE"
           "AGNXTIN"
           "AGPROTONODE"
           "GV-LAYOUT"
           "AGERRNO"
           "ATTRSYM-T"
           "AGFINDATTR"
           "BSEARCH-CMPF"
           "AGRESETERRORS"
           "AGFINDEDGE"
           "AGWRITE"
           "AGEDGEATTR"
           "AGFSTATTR"
           "AGERRORS"
           "AGDELETE"
           "AGLSTATTR"
           "AGLASTERR"
           "STROKES"
           "NSTROKES"
           "SHAPE-T"
           "AGSETIODISC"
           "NVERTICES"
           "STROKE-T"
           "AGNODEATTR"
           "AGPRVNODE"
           "AGPROTOEDGE"
           "GV-RENDER"
           "AGCONTAINS"
           "ATTACH-ATTRS"
           "GVC-INFO"
           "GETS-F"
           "AGCLOSE"
           "AGSTRDUP-HTML"
           "AGGRAPH"
           "AGNODE"
           "AGOBJKIND-T"
           "AGRAPHATTR"
           "IS-ORTHO"
           "IGNORE-SWAP"
           "SPLINE-MERGE"
           "SWAP-ENDS"
           "SPLINE-INFO"
           "AGINITLIB"
           "AGNNODES"
           "AGSETFILE"
           "AGUSERGRAPH"
           "AGSAFESET"
           "GVLAYOUT-FEATURES-T"
           "AGFSTOUT"
           "GV-FREE-LAYOUT"
           "AGNEDGES"
           "GV-FREE-CONTEXT"
           "LR"
           "FLD"
           "LP"
           "N-FLDS"
           "B"
           "FIELD-T"
           "AGATTR"
           "AGCOPYATTR"
           "AGPRVATTR"
           "AGEDGE"
           "AGINSERT"
           "AGFINDSUBG"
           "NBOX"
           "END"
           "START"
           "SH-EPSF"
           "SH-POINT"
           "SH-RECORD"
           "SH-POLY"
           "SH-UNSET"
           "SHAPE-KIND"
           "AGXSET"
           "AGWARNINGF"
           "T-0"
           "K"
           "TFACT"
           "C"
           "UNSCALED"
           "NUM-ITERS"
           "USE-NEW"
           "USE-GRID"
           "FDP-PARMS-T"
           "AGNXTNODE"
           "GV-RENDER-DATA"
           "GV-PLUGIN-LIST"
           "AGSETERRF"
           "AGUSERERRF"
           "AGERRORF"
           "AGPREV"
           "AGMAX"
           "AGERR"
           "AGWARN"
           "AGERRLEVEL-T"
           "GV-NE-WCONTEXT"
           "GV-RENDER-CONTEXT"
           "AGREAD"
           "FILE"
           "SIZE-T"
           "AGFSTEDGE"
           "POINT"
           "AGOPEN"
           "BOXES"
           "BOXN"
           "SIDEMASK"
           "NP"
           "NB"
           "PATHEND-T"
           "GV-RENDER-JOBS"
           "AGREADLINE"
           "GV-PARSE-ARGS"
           "AGCANON"
           "GV-TOGGLE"
           "AGINDEX"
           "AGMEMREAD"
           "AGFSTIN"
           "AGNXTATTR"
           "AGNXTEDGE"
           "TAIL"
           "HEAD"
           "TO-VIRT"
           "MINLEN"
           "COUNT"
           "TREE-INDEX"
           "CUTVALUE"
           "WEIGHT"
           "XPENALTY"
           "CONC-OPP-FLAG"
           "PATH"
           "FACTOR"
           "TO-ORIG"
           "LABEL-ONTOP"
           "ADJACENT"
           "EDGE-TYPE"
           "TAIL-LABEL"
           "HEAD-LABEL"
           "HEAD-PORT"
           "TAIL-PORT"
           "SPL"
           "AGEDGEINFO-T"
           "PPOLYLINE-T"
           "PN"
           "PS"
           "PPOLY-T"
           "PPOINT-T"
           "SIDE"
           "DYNA"
           "CLIP"
           "CONSTRAINED"
           "DEFINED"
           "BP"
           "THETA"
           "P"
           "PORT"
           "SPLINES"
           "EP"
           "SP"
           "EFLAG"
           "SFLAG"
           "BEZIER"
           "GRAPH"
           "PAD"
           "PRIORITY"
           "LIM"
           "LOW"
           "PAR"
           "TREE-OUT"
           "TREE-IN"
           "SAVE-OUT"
           "SAVE-IN"
           "MVAL"
           "ORDER"
           "OUTLEAF"
           "INLEAF"
           "UF-PARENT"
           "UF-SIZE"
           "OTHER"
           "FLAT-IN"
           "FLAT-OUT"
           "OUT"
           "IN"
           "NEXT"
           "WEIGHT-CLASS"
           "RANKTYPE"
           "ONSTACK"
           "MARK"
           "NODE-TYPE"
           "HAS-PORT"
           "HOPS"
           "HEAPINDEX"
           "PINNED"
           "CLUSTNODE"
           "STATE"
           "XLABEL"
           "RW"
           "LW"
           "HT"
           "HEIGHT"
           "WIDTH"
           "COORD"
           "SHAPE-INFO"
           "SHAPE"
           "AGNODEINFO-T"
           "ELIST"
           "AGEDGE-T"
           "EDGE-T"
           "USERSHAPE"
           "POLYGON"
           "FNS"
           "SHAPE-DESC"
           "VERTICES"
           "OPTION"
           "SKEW"
           "DISTORTION"
           "ORIENTATION"
           "SIDES"
           "PERIPHERIES"
           "REGULAR"
           "POLYGON-T"
           "CODEFN"
           "PBOXFN"
           "INSIDEFN"
           "PORTFN"
           "FREEFN"
           "INITFN"
           "SHAPE-FUNCTIONS"
           "PROTO"
           "META-NODE"
           "ROOT"
           "OUTEDGES"
           "INEDGES"
           "NODES"
           "UNIV"
           "DIDSET"
           "ATTR"
           "EXACT-RANKSEP"
           "LABEL-POS"
           "SET-TYPE"
           "INSTALLED"
           "EXPANDED"
           "RANKLEADER"
           "LEADER"
           "RN"
           "LN"
           "RANKSEP"
           "NODESEP"
           "FONTNAMES"
           "CLUSTER-WAS-COLLAPSED"
           "SHOWBOXES"
           "HAS-FLAT-EDGES"
           "MAXRANK"
           "MINRANK"
           "N-NODES"
           "MAXSET"
           "MINSET"
           "COMP"
           "RANK"
           "NLIST"
           "CLUST"
           "N-CLUSTER"
           "ODIM"
           "NDIM"
           "T"
           "SUM-T"
           "SPRING"
           "DIST"
           "MOVE"
           "NEATO-NLIST"
           "CLEANUP"
           "GVC"
           "ALG"
           "FLAGS"
           "RANKDIR"
           "HAS-IMAGES"
           "HAS-LABELS"
           "GUI-STATE"
           "BORDER"
           "BB"
           "LABEL"
           "DRAWING"
           "AGRAPHINFO-T"
           "SVGFONTS"
           "PSFONTS"
           "NATIVEFONTS"
           "FONTNAME-KIND"
           "NLIST-T"
           "FLAT"
           "CACHE-NC"
           "VALID"
           "CANDIDATE"
           "PHT-2"
           "PHT-1"
           "HT-2"
           "HT-1"
           "AV"
           "AN"
           "V"
           "RANK-T"
           "NCOLS"
           "NROWS"
           "ADJMATRIX-T"
           "AGRAPH-T"
           "GRAPH-T"
           "AGNODE-T"
           "NODE-T"
           "UR"
           "LL"
           "BOXF"
           "HTML"
           "SET"
           "VALIGN"
           "U"
           "POS"
           "SPACE"
           "DIMEN"
           "FONTSIZE"
           "CHARSET"
           "FONTCOLOR"
           "FONTNAME"
           "TEXT"
           "TEXTLABEL-T"
           "ID"
           "XDOTS"
           "RATIO-KIND"
           "CENTERED"
           "LANDSCAPE"
           "FILLED"
           "PAGE"
           "MARGIN"
           "DPI"
           "RATIO"
           "SCALE"
           "QUANTUM"
           "LAYOUT-T"
           "R-EXPAND"
           "R-AUTO"
           "R-COMPRESS"
           "R-FILL"
           "R-VALUE"
           "R-NONE"
           "RATIO-T"
           "BOOLEAN"
           "POINTF"
           "Y"
           "X"
           "POINTF-S"
           "PREV"
           "E"
           "N"
           "AGPROTO-T"
           "MAX-EDGE-ID"
           "MAX-NODE-ID"
           "GLOBATTR"
           "EDGEATTR"
           "NODEATTR"
           "NODE-DICT"
           "AGDATA-T"
           "LIST"
           "DICT"
           "AGDICT-T"
           "FIXED"
           "PRINTED"
           "INDEX"
           "VALUE"
           "AGSYM-T"
           "DICT-T"
           "USER"
           "WALK"
           "VIEW"
           "NVIEW"
           "METH"
           "DATA"
           "DISC"
           "DT-T"
           "DTMETHOD-T"
           "SEARCHF"
           "DTDATA-T"
           "MINP"
           "LOOP"
           "NTAB"
           "HH"
           "HERE"
           "TYPE"
           "DTLINK-T"
           "HL"
           "RIGHT"
           "DTDISC-T"
           "EVENTF"
           "MEMORYF"
           "HASHF"
           "COMPARF"
           "FREEF"
           "MAKEF"
           "LINK"
           "SIZE"
           "KEY"
           "DTEVENT-F"
           "DTMEMORY-F"
           "DTHASH-F"
           "DTCOMPAR-F"
           "DTFREE-F"
           "DTMAKE-F"
           "DTSEARCH-F"
           "GV-CONTEXT-PLUGINS"
           "ADDRESS"
           "NAME"
           "LT-SYMLIST-T"
           "GVC-T"
           "GVC-S"))

(cl:in-package :graphviz-cffi-bindings)

(cl:defun vtable-lookup (pobj indx coff)
  (cl:let ((vptr (cffi:mem-ref pobj :pointer coff)))
    (cffi:mem-aref vptr :pointer (cl:- indx 2))))

(cl:defmacro virtual-funcall (pobj indx coff cl:&body body)
  `(cffi:foreign-funcall-pointer (vtable-lookup ,pobj ,indx ,coff) ,cl:nil ,@body))

(cffi:defcstruct gvc-s
	)

(cffi::defctype gvc-t gvc-s)

(cffi:defcstruct lt-symlist-t
  (name :pointer)
  (address (:pointer :void)))

(cffi:defcfun ("gvContextPlugins" gv-context-plugins) :pointer (builtins :pointer)
                                                               (demand-loading :int))

(cffi::defctype dtsearch-f :pointer)

(cffi::defctype dtmake-f :pointer)

(cffi::defctype dtfree-f :pointer)

(cffi::defctype dtcompar-f :pointer)

(cffi::defctype dthash-f :pointer)

(cffi::defctype dtmemory-f :pointer)

(cffi::defctype dtevent-f :pointer)

(cffi:defcstruct _dtdisc-s
  (key :int)
  (size :int)
  (link :int)
  (makef dtmake-f)
  (freef dtfree-f)
  (comparf dtcompar-f)
  (hashf dthash-f)
  (memoryf dtmemory-f)
  (eventf dtevent-f))

(cffi::defctype dtdisc-t _dtdisc-s)

(cffi:defcunion _dtlink-s-inside-anon-union
  (_hash :unsigned-int)
  (_left :pointer )) ; (:pointer dtlink-t)

(cffi:defcstruct _dtlink-s
  (right :pointer)
  (hl _dtlink-s-inside-anon-union ))

(cffi::defctype dtlink-t _dtlink-s)

(cffi:defcunion _dtdata-s-inside-anon-union
   (_htab (:pointer (:pointer DTLINK-T)))
   (_head (:pointer DTLINK-T)))

(cffi:defcstruct _dtdata-s
  (type :int)
  (here :pointer)
  (hh _dtdata-s-inside-anon-union)
  (ntab :int)
  (size :int)
  (loop :int)
  (minp :int))

(cffi::defctype dtdata-t _dtdata-s)

(cffi:defcstruct _dtmethod-s
  (searchf dtsearch-f)
  (type :int))

(cffi::defctype dtmethod-t _dtmethod-s)

(cffi:defcstruct _dt-s
  (searchf dtsearch-f)
  (disc :pointer)
  (data :pointer)
  (memoryf dtmemory-f)
  (meth :pointer)
  (type :int)
  (nview :int)
  (view :pointer)
  (walk :pointer)
  (user (:pointer :void)))

(cffi::defctype dt-t _dt-s)

(cffi::defctype dict-t _dt-s)

(cffi:defcstruct agsym-t
  (name (:pointer :char))
  (value (:pointer :char))
  (index :int)
  (printed :unsigned-char)
  (fixed :unsigned-char))

(cffi:defcstruct agdict-t
  (name (:pointer :char))
  (dict :pointer)
  (list :pointer))

(cffi:defcstruct agdata-t
  (node-dict :pointer)
  (nodeattr :pointer)
  (edgeattr :pointer)
  (globattr :pointer)
  (max-node-id :int)
  (max-edge-id :int))

(cffi:defcstruct agproto-t
  (n :pointer)
  (e :pointer)
  (prev :pointer))

(cffi:defcstruct pointf-s
  (x :double)
  (y :double))

(cffi::defctype pointf pointf-s)

(cffi::defctype boolean :unsigned-char)

(cffi:defcenum ratio-t
  (:r-none 0)
  (:r-value 1)
  (:r-fill 2)
  (:r-compress 3)
  (:r-auto 4)
  (:r-expand 5))

(cffi:defcstruct layout-t
  (quantum :double)
  (scale :double)
  (ratio :double)
  (dpi :double)
  (margin pointf)
  (page pointf)
  (size pointf)
  (filled boolean)
  (landscape boolean)
  (centered boolean)
  (ratio-kind ratio-t)
  (xdots (:pointer :void))
  (id (:pointer :char)))

(cffi:defcstruct textpara-t
  (str (:pointer :char))
  (postscript-alias :pointer)
  (layout (:pointer :void))
  (free-layout :pointer)
  (font :pointer)
  (fontname (:pointer :char))
  (fontsize :double)
  (size :double)
  (yoffset-layout :double)
  (yoffset-centerline :double)
  (width :double)
  (height :double)
  (just :char))


(cffi:defcstruct textlabel-t-inside-anon-struct
  (para (:pointer textpara-t))
  (nparas :short))

(cffi:defcunion textlabel-t-inside-anon-union
  (txt textlabel-t-inside-anon-struct)
  (html :pointer)) ; (:pointer htmllabel-t) - htmllable is undefined

(cffi:defcstruct textlabel-t
  (text (:pointer :char))
  (fontname (:pointer :char))
  (fontcolor (:pointer :char))
  (charset :int)
  (fontsize :double)
  (dimen pointf)
  (space pointf)
  (pos pointf)
  (u textlabel-t-inside-anon-union)
  (valign :char)
  (set boolean)
  (html boolean))

(cffi:defcstruct boxf
  (ll pointf)
  (ur pointf))

(cffi:defcstruct adjmatrix-t
  (nrows :int)
  (ncols :int)
  (data (:pointer :char)))

(cffi:defcstruct rank-t
  (n :int)
  (v :pointer)
  (an :int)
  (av :pointer)
  (ht-1 :int)
  (ht-2 :int)
  (pht-1 :int)
  (pht-2 :int)
  (candidate boolean)
  (valid boolean)
  (cache-nc :int)
  (flat :pointer))

(cffi:defcstruct nlist-t
  (list :pointer)
  (size :int))

(cffi:defcenum fontname-kind
  (:nativefonts 0)
  (:psfonts 1)
  (:svgfonts 2))

(cffi:defcstruct agraphinfo-t
  (drawing :pointer)
  (label :pointer)
  (bb boxf)
  (border pointf :count 4)
  (gui-state :unsigned-char)
  (has-labels :unsigned-char)
  (has-images boolean)
  (charset :unsigned-char)
  (rankdir :int)
  (ht-1 :int)
  (ht-2 :int)
  (flags :unsigned-short)
  (alg (:pointer :void))
  (gvc :pointer)
  (cleanup :pointer)
  (neato-nlist :pointer)
  (move :int)
  (dist :pointer)
  (spring :pointer)
  (sum-t :pointer)
  (t :pointer)
  (ndim :unsigned-short)
  (odim :unsigned-short)
  (n-cluster :int)
  (clust :pointer)
  (nlist :pointer)
  (rank :pointer)
  (comp nlist-t)
  (minset :pointer)
  (maxset :pointer)
  (n-nodes :long)
  (minrank :short)
  (maxrank :short)
  (has-flat-edges boolean)
  (showboxes :unsigned-char)
  (cluster-was-collapsed boolean)
  (fontnames fontname-kind)
  (nodesep :int)
  (ranksep :int)
  (ln :pointer)
  (rn :pointer)
  (leader :pointer)
  (rankleader :pointer)
  (expanded boolean)
  (installed :char)
  (set-type :char)
  (label-pos :char)
  (exact-ranksep boolean))

(cffi:defcstruct agraph-t
  ;;; Skipping field #<FIELD tag> in #<STRUCT
  ;                                     Agraph_t> because it has a bitfield type which is not yet supported by CFFI! Check the layout manually!

  ;;; Skipping field #<FIELD kind> in #<STRUCT
  ;                                      Agraph_t> because it has a bitfield type which is not yet supported by CFFI! Check the layout manually!

  ;;; Skipping field #<FIELD handle> in #<STRUCT
  ;                                        Agraph_t> because it has a bitfield type which is not yet supported by CFFI! Check the layout manually!
  
  (padding1 :int) ;; generated to pad 32 bits of skipped bitfield typed fields
  (attr :pointer)
  (didset (:pointer :char))
  (name (:pointer :char))
  (univ :pointer)
  (nodes :pointer)
  (inedges :pointer)
  (outedges :pointer)
  (root :pointer)
  (meta-node :pointer)
  (proto :pointer)
  (u agraphinfo-t))

(cffi::defctype graph-t agraph-t)

(cffi:defcstruct shape-functions
  (initfn :pointer)
  (freefn :pointer)
  (portfn :pointer)
  (insidefn :pointer)
  (pboxfn :pointer)
  (codefn :pointer))

(cffi:defcstruct polygon-t
  (regular :int)
  (peripheries :int)
  (sides :int)
  (orientation :double)
  (distortion :double)
  (skew :double)
  (option :int)
  (vertices :pointer))

(cffi:defcstruct shape-desc
  (name (:pointer :char))
  (fns :pointer)
  (polygon :pointer)
  (usershape boolean))

(cffi:defcstruct elist
  (list :pointer)
  (size :int))

(cffi:defcstruct agnodeinfo-t
  (shape :pointer)
  (shape-info (:pointer :void))
  (coord pointf)
  (width :double)
  (height :double)
  (bb boxf)
  (ht :double)
  (lw :double)
  (rw :double)
  (label :pointer)
  (xlabel :pointer)
  (alg (:pointer :void))
  (state :char)
  (gui-state :unsigned-char)
  (clustnode boolean)
  (pinned :unsigned-char)
  (id :int)
  (heapindex :int)
  (hops :int)
  (pos (:pointer :double))
  (dist :double)
  (showboxes :unsigned-char)
  (has-port boolean)
  (node-type :char)
  (mark :char)
  (onstack :char)
  (ranktype :char)
  (weight-class :char)
  (next :pointer)
  (prev :pointer)
  (in elist)
  (out elist)
  (flat-out elist)
  (flat-in elist)
  (other elist)
  (clust :pointer)
  (uf-size :int)
  (uf-parent :pointer)
  (inleaf :pointer)
  (outleaf :pointer)
  (rank :int)
  (order :int)
  (mval :int)
  (save-in elist)
  (save-out elist)
  (tree-in elist)
  (tree-out elist)
  (par :pointer)
  (low :int)
  (lim :int)
  (priority :int)
  (pad :double :count 1))

(cffi:defcstruct agnode-t
  ;;; Skipping field #<FIELD tag> in #<STRUCT
  ;                                     Agnode_t> because it has a bitfield type which is not yet supported by CFFI! Check the layout manually!

  ;;; Skipping field #<FIELD pad> in #<STRUCT
  ;                                     Agnode_t> because it has a bitfield type which is not yet supported by CFFI! Check the layout manually!

  ;;; Skipping field #<FIELD handle> in #<STRUCT
  ;                                        Agnode_t> because it has a bitfield type which is not yet supported by CFFI! Check the layout manually!
  
  (padding2 :int) ;; generated to pad 32 bits of skipped bitfield typed fields
  (attr :pointer)
  (didset (:pointer :char))
  (name (:pointer :char))
  (id :int)
  (graph :pointer)
  (u agnodeinfo-t))

(cffi::defctype node-t agnode-t)


(cffi:defcstruct bezier
  (list :pointer)
  (size :int)
  (sflag :int)
  (eflag :int)
  (sp pointf)
  (ep pointf))

(cffi:defcstruct splines
  (list :pointer)
  (size :int)
  (bb boxf))

(cffi:defcstruct port
  (p pointf)
  (theta :double)
  (bp :pointer)
  (defined boolean)
  (constrained boolean)
  (clip boolean)
  (dyna boolean)
  (order :unsigned-char)
  (side :unsigned-char)
  (name (:pointer :char)))

(cffi::defctype ppoint-t pointf-s)

(cffi:defcstruct ppoly-t
  (ps :pointer)
  (pn :int))

(cffi::defctype ppolyline-t ppoly-t)

(cffi:defcstruct agedgeinfo-t
  (spl :pointer)
  (tail-port port)
  (head-port port)
  (label :pointer)
  (head-label :pointer)
  (tail-label :pointer)
  (xlabel :pointer)
  (edge-type :char)
  (adjacent :char)
  (label-ontop :char)
  (gui-state :unsigned-char)
  (to-orig :pointer)
  (alg (:pointer :void))
  (factor :double)
  (dist :double)
  (path ppolyline-t)
  (showboxes :unsigned-char)
  (conc-opp-flag boolean)
  (xpenalty :short)
  (weight :float)
  (cutvalue :int)
  (tree-index :int)
  (count :short)
  (minlen :unsigned-short)
  (to-virt :pointer))

(cffi:defcstruct agedge-t
  ;;; Skipping field #<FIELD tag> in #<STRUCT
  ;                                     Agedge_t> because it has a bitfield type which is not yet supported by CFFI! Check the layout manually!

  ;;; Skipping field #<FIELD printkey> in #<STRUCT
  ;                                          Agedge_t> because it has a bitfield type which is not yet supported by CFFI! Check the layout manually!

  ;;; Skipping field #<FIELD handle> in #<STRUCT
  ;                                        Agedge_t> because it has a bitfield type which is not yet supported by CFFI! Check the layout manually!
  
  (padding3 :int) ;; generated to pad 32 bits of skipped bitfield typed fields
  (attr :pointer)
  (didset (:pointer :char))
  (head :pointer)
  (tail :pointer)
  (id :int)
  (u agedgeinfo-t))

(cffi::defctype edge-t agedge-t)

(cffi:defcfun ("agnxtedge" agnxtedge) :pointer (arg1 :pointer) (arg2 :pointer) (arg3 :pointer))

(cffi:defcfun ("agnxtattr" agnxtattr) :pointer (arg1 (:pointer :void)) (arg2 :pointer))

(cffi:defcfun ("agfstin" agfstin) :pointer (arg1 :pointer) (arg2 :pointer))

(cffi:defcfun ("agmemread" agmemread) :pointer (arg1 (:pointer :char)))

(cffi:defcfun ("agindex" agindex) :int (arg1 (:pointer :void)) (arg2 (:pointer :char)))

(cffi:defcfun ("gvToggle" gv-toggle) :void (arg1 :int))

(cffi:defcfun ("agcanon" agcanon) (:pointer :char) (arg1 (:pointer :char)))

(cffi:defcfun ("gvParseArgs" gv-parse-args) :int (gvc :pointer) (argc :int) (argv :pointer))

(cffi:defcfun ("agreadline" agreadline) :void (arg1 :int))

(cffi:defcfun ("gvRenderJobs" gv-render-jobs) :int (gvc :pointer) (g :pointer))

(cffi:defcstruct pathend-t
  (nb boxf)
  (np pointf)
  (sidemask :int)
  (boxn :int)
  (boxes boxf :count 20))

(cffi:defcfun ("agopen" agopen) :pointer (arg1 (:pointer :char)) (arg2 :int))

(cffi:defcstruct point
  (x :int)
  (y :int))

(cffi:defcfun ("agfstedge" agfstedge) :pointer (arg1 :pointer) (arg2 :pointer))

(cffi:defcstruct _io-marker
  (_next :pointer)
  (_sbuf :pointer)
  (_pos :int))

(cffi::defctype _-off-t :long)

(cffi::defctype _io-lock-t :void)

(cffi::defctype _-quad-t :long-long)

(cffi::defctype _-off-64-t _-quad-t)

(cffi::defctype size-t :unsigned-int)

(cffi:defcstruct _io-file
  (_flags :int)
  (_io-read-ptr (:pointer :char))
  (_io-read-end (:pointer :char))
  (_io-read-base (:pointer :char))
  (_io-write-base (:pointer :char))
  (_io-write-ptr (:pointer :char))
  (_io-write-end (:pointer :char))
  (_io-buf-base (:pointer :char))
  (_io-buf-end (:pointer :char))
  (_io-save-base (:pointer :char))
  (_io-backup-base (:pointer :char))
  (_io-save-end (:pointer :char))
  (_markers :pointer)
  (_chain :pointer)
  (_fileno :int)
  (_flags-2 :int)
  (_old-offset _-off-t)
  (_cur-column :unsigned-short)
  (_vtable-offset :char)
  (_shortbuf :char :count 1)
  (_lock :pointer)
  (_offset _-off-64-t)
  (_-pad-1 (:pointer :void))
  (_-pad-2 (:pointer :void))
  (_-pad-3 (:pointer :void))
  (_-pad-4 (:pointer :void))
  (_-pad-5 size-t)
  (_mode :int)
  (_unused-2 :char :count 40))

(cffi::defctype file _io-file)

(cffi:defcfun ("agread" agread) :pointer (arg1 :pointer))

(cffi:defcfun ("gvRenderContext" gv-render-context) :int (gvc :pointer) (g :pointer)
                                                         (format :pointer)
                                                         (context (:pointer :void)))

(cffi:defcfun ("gvNEWcontext" gv-ne-wcontext) :pointer (builtins :pointer) (demand-loading :int))

(cffi:defcenum agerrlevel-t
  (:agwarn 0)
  (:agerr 1)
  (:agmax 2)
  (:agprev 3))

(cffi:defcfun ("agerrorf" agerrorf) :void (fmt :pointer)common-lisp:&rest)

(cffi::defctype agusererrf :pointer)

(cffi:defcfun ("agseterrf" agseterrf) agusererrf (arg1 agusererrf))

(cffi:defcfun ("gvPluginList" gv-plugin-list) :pointer (gvc :pointer) (kind (:pointer :char))
                                                       (sz (:pointer :int)) (arg4 (:pointer :char)))

(cffi:defcfun ("gvRenderData" gv-render-data) :int (gvc :pointer) (g :pointer) (format :pointer)
                                                   (result :pointer)
                                                   (length (:pointer :unsigned-int)))

(cffi:defcfun ("agnxtnode" agnxtnode) :pointer (arg1 :pointer) (arg2 :pointer))

(cffi:defcstruct fdp-parms-t
  (use-grid :int)
  (use-new :int)
  (num-iters :int)
  (unscaled :int)
  (c :double)
  (tfact :double)
  (k :double)
  (t-0 :double))

(cffi:defcfun ("agwarningf" agwarningf) :void (fmt (:pointer :char))common-lisp:&rest)

(cffi:defcfun ("agxset" agxset) :int (arg1 (:pointer :void)) (arg2 :int) (arg3 (:pointer :char)))

(cffi:defcenum shape-kind
  (:sh-unset 0)
  (:sh-poly 1)
  (:sh-record 2)
  (:sh-point 3)
  (:sh-epsf 4))

(cffi:defcstruct path
  (start port)
  (end port)
  (nbox :int)
  (boxes :pointer)
  (data (:pointer :void)))

(cffi:defcfun ("agfindsubg" agfindsubg) :pointer (arg1 :pointer) (arg2 (:pointer :char)))

(cffi:defcfun ("aginsert" aginsert) :void (arg1 :pointer) (arg2 (:pointer :void)))

(cffi:defcfun ("agedge" agedge) :pointer (arg1 :pointer) (arg2 :pointer) (arg3 :pointer))

(cffi:defcfun ("agprvattr" agprvattr) :pointer (arg1 (:pointer :void)) (arg2 :pointer))

(cffi:defcfun ("agcopyattr" agcopyattr) :int (arg1 (:pointer :void)) (arg2 (:pointer :void)))

(cffi:defcfun ("agattr" agattr) :pointer (arg1 (:pointer :void)) (arg2 (:pointer :char))
                                         (arg3 (:pointer :char)))

(cffi:defcstruct field-t
  (size pointf)
  (b boxf)
  (n-flds :int)
  (lp :pointer)
  (fld :pointer)
  (id (:pointer :char))
  (lr :unsigned-char)
  (sides :unsigned-char))

(cffi:defcfun ("agerr" agerr) :int (level agerrlevel-t) (fmt (:pointer :char))common-lisp:&rest)

(cffi:defcfun ("gvFreeContext" gv-free-context) :int (gvc :pointer))

(cffi:defcfun ("agnedges" agnedges) :int (arg1 :pointer))

(cffi:defcfun ("gvFreeLayout" gv-free-layout) :int (gvc :pointer) (g :pointer))

(cffi:defcfun ("agfstout" agfstout) :pointer (arg1 :pointer) (arg2 :pointer))

(cffi:defcstruct gvlayout-features-t
  (flags :int))

(cffi:defcfun ("agsafeset" agsafeset) :int (arg1 (:pointer :void)) (arg2 (:pointer :char))
                                           (arg3 (:pointer :char)) (arg4 (:pointer :char)))

(cffi:defcfun ("agusergraph" agusergraph) :pointer (arg1 :pointer))

(cffi:defcfun ("agsetfile" agsetfile) :void (arg1 (:pointer :char)))

(cffi:defcfun ("agnnodes" agnnodes) :int (arg1 :pointer))

(cffi:defcfun ("aginitlib" aginitlib) :void (arg1 :int) (arg2 :int) (arg3 :int))

(cffi:defcstruct spline-info
  (swap-ends :pointer)
  (spline-merge :pointer)
  (ignore-swap boolean)
  (is-ortho boolean))

(cffi:defcfun ("agraphattr" agraphattr) :pointer (arg1 :pointer) (arg2 (:pointer :char))
                                                 (arg3 (:pointer :char)))

(cffi:defcenum agobjkind-t
  (:agnode 1)
  (:agedge 2)
  (:aggraph 3))

(cffi:defcfun ("agstrdup_html" agstrdup-html) (:pointer :char) (s (:pointer :char)))

(cffi:defcfun ("agclose" agclose) :void (arg1 :pointer))

(cffi::defctype gets-f :pointer)

(cffi:defcfun ("gvcInfo" gvc-info) :pointer (arg1 :pointer))

(cffi:defcfun ("attach_attrs" attach-attrs) :void (g :pointer))

(cffi:defcfun ("agcontains" agcontains) :int (arg1 :pointer) (arg2 (:pointer :void)))

(cffi:defcfun ("gvRender" gv-render) :int (gvc :pointer) (g :pointer) (format :pointer)
                                          (out :pointer))

(cffi:defcfun ("agprotoedge" agprotoedge) :pointer (arg1 :pointer))

(cffi:defcfun ("agprvnode" agprvnode) :pointer (arg1 :pointer) (arg2 :pointer))

(cffi:defcfun ("agnodeattr" agnodeattr) :pointer (arg1 :pointer) (arg2 (:pointer :char))
                                                 (arg3 (:pointer :char)))

(cffi:defcstruct stroke-t
  (nvertices :int)
  (flags :int)
  (vertices :pointer))

(cffi:defcfun ("agsetiodisc" agsetiodisc) :void (myfgets :pointer) (myfwrite :pointer)
                                                (myferror :pointer))

(cffi:defcstruct shape-t
  (nstrokes :int)
  (strokes :pointer))

(cffi:defcfun ("aglasterr" aglasterr) (:pointer :char))

(cffi:defcfun ("aglstattr" aglstattr) :pointer (arg1 (:pointer :void)))

(cffi:defcfun ("agdelete" agdelete) :void (arg1 :pointer) (arg2 (:pointer :void)))

(cffi:defcfun ("agerrors" agerrors) :int)

(cffi:defcfun ("agfstattr" agfstattr) :pointer (arg1 (:pointer :void)))

(cffi:defcfun ("agedgeattr" agedgeattr) :pointer (arg1 :pointer) (arg2 (:pointer :char))
                                                 (arg3 (:pointer :char)))

(cffi:defcfun ("agwrite" agwrite) :int (arg1 :pointer) (arg2 :pointer))

(cffi:defcfun ("agfindedge" agfindedge) :pointer (arg1 :pointer) (arg2 :pointer) (arg3 :pointer))

(cffi:defcfun ("agreseterrors" agreseterrors) :int)

(cffi::defctype bsearch-cmpf :pointer)

(cffi:defcfun ("agfindattr" agfindattr) :pointer (arg1 (:pointer :void)) (arg2 (:pointer :char)))

(cffi::defctype attrsym-t agsym-t)

(cffi:defcvar ("agerrno" agerrno) agerrlevel-t)

(cffi:defcfun ("gvLayout" gv-layout) :int (gvc :pointer) (g :pointer) (engine :pointer))

(cffi:defcfun ("agprotonode" agprotonode) :pointer (arg1 :pointer))

(cffi:defcfun ("agnxtin" agnxtin) :pointer (arg1 :pointer) (arg2 :pointer))

(cffi:defcfun ("gvcBuildDate" gvc-build-date) (:pointer :char) (arg1 :pointer))

(cffi:defcfun ("gvcVersion" gvc-version) (:pointer :char) (arg1 :pointer))

(cffi:defcfun ("agcanonical" agcanonical) (:pointer :char) (arg1 (:pointer :char)))

(cffi:defcstruct nodequeue
  (store :pointer)
  (limit :pointer)
  (head :pointer)
  (tail :pointer))

(cffi:defcfun ("agnxtout" agnxtout) :pointer (arg1 :pointer) (arg2 :pointer))
;;; Skipping anonymous composite type #<STRUCT <anonymous> {CB7C861}>
;;; Skipping anonymous composite type #<STRUCT <anonymous> {CB7C871}>

(cffi:defcfun ("gvLayoutJobs" gv-layout-jobs) :int (gvc :pointer) (g :pointer))

(cffi:defcfun ("agset" agset) :int (arg1 (:pointer :void)) (arg2 (:pointer :char))
                                   (arg3 (:pointer :char)))

(cffi:defcfun ("agstrfree" agstrfree) :void (arg1 (:pointer :char)))

(cffi:defcfun ("agputs" agputs) :int (s :pointer) (fp :pointer))

(cffi:defcfun ("agget" agget) (:pointer :char) (arg1 (:pointer :void)) (arg2 (:pointer :char)))

(cffi:defcfun ("agstrdup" agstrdup) (:pointer :char) (arg1 (:pointer :char)))

(cffi:defcfun ("agnode" agnode) :pointer (arg1 :pointer) (arg2 (:pointer :char)))

(cffi:defcfun ("gvRenderFilename" gv-render-filename) :int (gvc :pointer) (g :pointer)
                                                           (format :pointer) (filename :pointer))

(cffi:defcfun ("agprotograph" agprotograph) :pointer)

(cffi:defcfun ("agfstnode" agfstnode) :pointer (arg1 :pointer))

(cffi::defctype qsort-cmpf :pointer)

(cffi:defcfun ("agfindnode" agfindnode) :pointer (arg1 :pointer) (arg2 (:pointer :char)))

(cffi:defcfun ("gvFinalize" gv-finalize) :void (gvc :pointer))

(cffi:defcfun ("aghtmlstr" aghtmlstr) :int (s (:pointer :char)))

(cffi:defcfun ("agread_usergets" agread-usergets) :pointer (arg1 :pointer) (arg2 gets-f))

(cffi:defcstruct box
  (ll point)
  (ur point))

(cffi:defcfun ("agseterr" agseterr) :void (arg1 agerrlevel-t))

(cffi:defcfun ("agxget" agxget) (:pointer :char) (arg1 (:pointer :void)) (arg2 :int))

(cffi:defcenum api-t
  (:api-render 0)
  (:api-layout 1)
  (:api-textlayout 2)
  (:api-device 3)
  (:api-loadimage 4)
  (:_dummy-elem- 0))

(cffi:defcstruct gvplugin-installed-t
  (id :int)
  (type :pointer)
  (quality :int)
  (engine (:pointer :void))
  (features (:pointer :void)))

(cffi:defcstruct gvplugin-api-t
  (api api-t)
  (types :pointer))

(cffi:defcstruct gvplugin-library-t
  (packagename (:pointer :char))
  (apis :pointer))

(cffi:defcfun ("gvAddLibrary" gv-add-library) :void (gvc :pointer) (lib :pointer))

(cffi:defcfun ("gvNextInputGraph" gv-next-input-graph) :pointer (gvc :pointer))

(cffi:defcfun ("agsubg" agsubg) :pointer (arg1 :pointer) (arg2 (:pointer :char)))

(cffi:defcfun ("agstrcanon" agstrcanon) (:pointer :char) (arg1 (:pointer :char))
                                                         (arg2 (:pointer :char)))

(cffi:defcfun ("agputc" agputc) :int (c :int) (fp :pointer))

(cffi:defcfun ("aglstnode" aglstnode) :pointer (arg1 :pointer))

(cffi:defcfun ("gvPluginsGraph" gv-plugins-graph) :pointer (gvc :pointer))

(cffi:defcfun ("gvContext" gv-context) :pointer)

;;; Thats: VVVV all commented, because I don't know what is it for. 

#| ;IMHO It is something unnecessary. Maybe unwished trash.

(cffi:defcfun ("_ZN7Agsym_taSERKS_" agsym-t-operator-=) agsym-t (this :pointer) (arg1 agsym-t))

(cffi:defcfun ("_ZN7Agsym_tC1ERKS_" agsym-t-constructor) :void (this :pointer) (arg1 agsym-t))

(cl:defun agsym-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agsym-t)))
    (agsym-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN7Agsym_tC1Ev" agsym-t-constructor) :void (this :pointer))

(cl:defun agsym-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agsym-t)))
    (agsym-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN9polygon_taSERKS_" polygon-t-operator-=) polygon-t (this :pointer)
                                                                      (arg1 polygon-t))

(cffi:defcfun ("_ZN9polygon_tC1ERKS_" polygon-t-constructor) :void (this :pointer) (arg1 polygon-t))

(cl:defun polygon-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'polygon-t)))
    (polygon-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN9polygon_tC1Ev" polygon-t-constructor) :void (this :pointer))

(cl:defun polygon-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'polygon-t)))
    (polygon-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN12Agedgeinfo_taSERKS_" agedgeinfo-t-operator-=) agedgeinfo-t (this :pointer)
                                                                                (arg1 agedgeinfo-t))

(cffi:defcfun ("_ZN12Agedgeinfo_tC1ERKS_" agedgeinfo-t-constructor) :void (this :pointer)
                                                                          (arg1 agedgeinfo-t))

(cl:defun agedgeinfo-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agedgeinfo-t)))
    (agedgeinfo-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN12Agedgeinfo_tC1Ev" agedgeinfo-t-constructor) :void (this :pointer))

(cl:defun agedgeinfo-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agedgeinfo-t)))
    (agedgeinfo-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN7nlist_taSERKS_" nlist-t-operator-=) nlist-t (this :pointer) (arg1 nlist-t))

(cffi:defcfun ("_ZN7nlist_tC1ERKS_" nlist-t-constructor) :void (this :pointer) (arg1 nlist-t))

(cl:defun nlist-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'nlist-t)))
    (nlist-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN7nlist_tC1Ev" nlist-t-constructor) :void (this :pointer))

(cl:defun nlist-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'nlist-t)))
    (nlist-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN4portaSERKS_" port-operator-=) port (this :pointer) (arg1 port))

(cffi:defcfun ("_ZN4portC1ERKS_" port-constructor) :void (this :pointer) (arg1 port))

(cl:defun port-new ()
  (cl:let ((instance (cffi:foreign-alloc 'port)))
    (port-constructor instance)
    instance))

(cffi:defcfun ("_ZN4portC1Ev" port-constructor) :void (this :pointer))

(cl:defun port-new ()
  (cl:let ((instance (cffi:foreign-alloc 'port)))
    (port-constructor instance)
    instance))

(cffi:defcfun ("_ZN4boxfaSERKS_" boxf-operator-=) boxf (this :pointer) (arg1 boxf))

(cffi:defcfun ("_ZN9pathend_taSERKS_" pathend-t-operator-=) pathend-t (this :pointer)
                                                                      (arg1 pathend-t))

(cffi:defcfun ("_ZN9pathend_tC1ERKS_" pathend-t-constructor) :void (this :pointer) (arg1 pathend-t))

(cl:defun pathend-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'pathend-t)))
    (pathend-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN9pathend_tC1Ev" pathend-t-constructor) :void (this :pointer))

(cl:defun pathend-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'pathend-t)))
    (pathend-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN11adjmatrix_taSERKS_" adjmatrix-t-operator-=) adjmatrix-t (this :pointer)
                                                                             (arg1 adjmatrix-t))

(cffi:defcfun ("_ZN11adjmatrix_tC1ERKS_" adjmatrix-t-constructor) :void (this :pointer)
                                                                        (arg1 adjmatrix-t))

(cl:defun adjmatrix-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'adjmatrix-t)))
    (adjmatrix-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN11adjmatrix_tC1Ev" adjmatrix-t-constructor) :void (this :pointer))

(cl:defun adjmatrix-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'adjmatrix-t)))
    (adjmatrix-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN5pointaSERKS_" point-operator-=) point (this :pointer) (arg1 point))

(cffi:defcfun ("_ZN8layout_taSERKS_" layout-t-operator-=) layout-t (this :pointer) (arg1 layout-t))

(cffi:defcfun ("_ZN8layout_tC1ERKS_" layout-t-constructor) :void (this :pointer) (arg1 layout-t))

(cl:defun layout-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'layout-t)))
    (layout-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN8layout_tC1Ev" layout-t-constructor) :void (this :pointer))

(cl:defun layout-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'layout-t)))
    (layout-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN8Agdict_taSERKS_" agdict-t-operator-=) agdict-t (this :pointer) (arg1 agdict-t))

(cffi:defcfun ("_ZN8Agdict_tC1ERKS_" agdict-t-constructor) :void (this :pointer) (arg1 agdict-t))

(cl:defun agdict-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agdict-t)))
    (agdict-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN8Agdict_tC1Ev" agdict-t-constructor) :void (this :pointer))

(cl:defun agdict-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agdict-t)))
    (agdict-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN10fdpParms_taSERKS_" fdp-parms-t-operator-=) fdp-parms-t (this :pointer)
                                                                            (arg1 fdp-parms-t))

(cffi:defcfun ("_ZN8Agraph_taSERKS_" agraph-t-operator-=) agraph-t (this :pointer) (arg1 agraph-t))

(cffi:defcfun ("_ZN8Agraph_tC1ERKS_" agraph-t-constructor) :void (this :pointer) (arg1 agraph-t))

(cl:defun agraph-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agraph-t)))
    (agraph-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN8Agraph_tC1Ev" agraph-t-constructor) :void (this :pointer))

(cl:defun agraph-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agraph-t)))
    (agraph-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN4pathaSERKS_" path-operator-=) path (this :pointer) (arg1 path))

(cffi:defcfun ("_ZN4pathC1ERKS_" path-constructor) :void (this :pointer) (arg1 path))

(cl:defun path-new ()
  (cl:let ((instance (cffi:foreign-alloc 'path)))
    (path-constructor instance)
    instance))

(cffi:defcfun ("_ZN4pathC1Ev" path-constructor) :void (this :pointer))

(cl:defun path-new ()
  (cl:let ((instance (cffi:foreign-alloc 'path)))
    (path-constructor instance)
    instance))

(cffi:defcfun ("_ZN7field_taSERKS_" field-t-operator-=) field-t (this :pointer) (arg1 field-t))

(cffi:defcfun ("_ZN7field_tC1ERKS_" field-t-constructor) :void (this :pointer) (arg1 field-t))

(cl:defun field-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'field-t)))
    (field-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN7field_tC1Ev" field-t-constructor) :void (this :pointer))

(cl:defun field-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'field-t)))
    (field-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN9Agproto_taSERKS_" agproto-t-operator-=) agproto-t (this :pointer)
                                                                      (arg1 agproto-t))

(cffi:defcfun ("_ZN9Agproto_tC1ERKS_" agproto-t-constructor) :void (this :pointer) (arg1 agproto-t))

(cl:defun agproto-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agproto-t)))
    (agproto-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN9Agproto_tC1Ev" agproto-t-constructor) :void (this :pointer))

(cl:defun agproto-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agproto-t)))
    (agproto-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN8Agdata_taSERKS_" agdata-t-operator-=) agdata-t (this :pointer) (arg1 agdata-t))

(cffi:defcfun ("_ZN8Agdata_tC1ERKS_" agdata-t-constructor) :void (this :pointer) (arg1 agdata-t))

(cl:defun agdata-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agdata-t)))
    (agdata-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN8Agdata_tC1Ev" agdata-t-constructor) :void (this :pointer))

(cl:defun agdata-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agdata-t)))
    (agdata-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN19gvlayout_features_taSERKS_" gvlayout-features-t-operator-=) gvlayout-features-t (this :pointer)
                                                                                                     (arg1 gvlayout-features-t))

(cffi:defcfun ("_ZN6bezieraSERKS_" bezier-operator-=) bezier (this :pointer) (arg1 bezier))

(cffi:defcfun ("_ZN6bezierC1ERKS_" bezier-constructor) :void (this :pointer) (arg1 bezier))

(cl:defun bezier-new ()
  (cl:let ((instance (cffi:foreign-alloc 'bezier)))
    (bezier-constructor instance)
    instance))

(cffi:defcfun ("_ZN6bezierC1Ev" bezier-constructor) :void (this :pointer))

(cl:defun bezier-new ()
  (cl:let ((instance (cffi:foreign-alloc 'bezier)))
    (bezier-constructor instance)
    instance))

(cffi:defcfun ("_ZN10splineInfoaSERKS_" spline-info-operator-=) spline-info (this :pointer)
                                                                            (arg1 spline-info))

(cffi:defcfun ("_ZN8stroke_taSERKS_" stroke-t-operator-=) stroke-t (this :pointer) (arg1 stroke-t))

(cffi:defcfun ("_ZN8stroke_tC1ERKS_" stroke-t-constructor) :void (this :pointer) (arg1 stroke-t))

(cl:defun stroke-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'stroke-t)))
    (stroke-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN8stroke_tC1Ev" stroke-t-constructor) :void (this :pointer))

(cl:defun stroke-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'stroke-t)))
    (stroke-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN7splinesaSERKS_" splines-operator-=) splines (this :pointer) (arg1 splines))

(cffi:defcfun ("_ZN7splinesC1ERKS_" splines-constructor) :void (this :pointer) (arg1 splines))

(cl:defun splines-new ()
  (cl:let ((instance (cffi:foreign-alloc 'splines)))
    (splines-constructor instance)
    instance))

(cffi:defcfun ("_ZN7splinesC1Ev" splines-constructor) :void (this :pointer))

(cl:defun splines-new ()
  (cl:let ((instance (cffi:foreign-alloc 'splines)))
    (splines-constructor instance)
    instance))

(cffi:defcfun ("_ZN8pointf_saSERKS_" pointf-s-operator-=) pointf-s (this :pointer) (arg1 pointf-s))

(cffi:defcfun ("_ZN8pointf_sC1ERKS_" pointf-s-constructor) :void (this :pointer) (arg1 pointf-s))

(cl:defun pointf-s-new ()
  (cl:let ((instance (cffi:foreign-alloc 'pointf-s)))
    (pointf-s-constructor instance)
    instance))

(cffi:defcfun ("_ZN8pointf_sC1Ev" pointf-s-constructor) :void (this :pointer))

(cl:defun pointf-s-new ()
  (cl:let ((instance (cffi:foreign-alloc 'pointf-s)))
    (pointf-s-constructor instance)
    instance))

(cffi:defcfun ("_ZN7shape_taSERKS_" shape-t-operator-=) shape-t (this :pointer) (arg1 shape-t))

(cffi:defcfun ("_ZN7shape_tC1ERKS_" shape-t-constructor) :void (this :pointer) (arg1 shape-t))

(cl:defun shape-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'shape-t)))
    (shape-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN7shape_tC1Ev" shape-t-constructor) :void (this :pointer))

(cl:defun shape-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'shape-t)))
    (shape-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN12Agnodeinfo_taSERKS_" agnodeinfo-t-operator-=) agnodeinfo-t (this :pointer)
                                                                                (arg1 agnodeinfo-t))

(cffi:defcfun ("_ZN12Agnodeinfo_tC1ERKS_" agnodeinfo-t-constructor) :void (this :pointer)
                                                                          (arg1 agnodeinfo-t))

(cl:defun agnodeinfo-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agnodeinfo-t)))
    (agnodeinfo-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN12Agnodeinfo_tC1Ev" agnodeinfo-t-constructor) :void (this :pointer))

(cl:defun agnodeinfo-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agnodeinfo-t)))
    (agnodeinfo-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN6rank_taSERKS_" rank-t-operator-=) rank-t (this :pointer) (arg1 rank-t))

(cffi:defcfun ("_ZN6rank_tC1ERKS_" rank-t-constructor) :void (this :pointer) (arg1 rank-t))

(cl:defun rank-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'rank-t)))
    (rank-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN6rank_tC1Ev" rank-t-constructor) :void (this :pointer))

(cl:defun rank-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'rank-t)))
    (rank-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN10shape_descaSERKS_" shape-desc-operator-=) shape-desc (this :pointer)
                                                                          (arg1 shape-desc))

(cffi:defcfun ("_ZN10shape_descC1ERKS_" shape-desc-constructor) :void (this :pointer)
                                                                      (arg1 shape-desc))

(cl:defun shape-desc-new ()
  (cl:let ((instance (cffi:foreign-alloc 'shape-desc)))
    (shape-desc-constructor instance)
    instance))

(cffi:defcfun ("_ZN10shape_descC1Ev" shape-desc-constructor) :void (this :pointer))

(cl:defun shape-desc-new ()
  (cl:let ((instance (cffi:foreign-alloc 'shape-desc)))
    (shape-desc-constructor instance)
    instance))

(cffi:defcfun ("_ZN8Agnode_taSERKS_" agnode-t-operator-=) agnode-t (this :pointer) (arg1 agnode-t))

(cffi:defcfun ("_ZN8Agnode_tC1ERKS_" agnode-t-constructor) :void (this :pointer) (arg1 agnode-t))

(cl:defun agnode-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agnode-t)))
    (agnode-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN8Agnode_tC1Ev" agnode-t-constructor) :void (this :pointer))

(cl:defun agnode-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agnode-t)))
    (agnode-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN8Agedge_taSERKS_" agedge-t-operator-=) agedge-t (this :pointer) (arg1 agedge-t))

(cffi:defcfun ("_ZN8Agedge_tC1ERKS_" agedge-t-constructor) :void (this :pointer) (arg1 agedge-t))

(cl:defun agedge-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agedge-t)))
    (agedge-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN8Agedge_tC1Ev" agedge-t-constructor) :void (this :pointer))

(cl:defun agedge-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agedge-t)))
    (agedge-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN9nodequeueaSERKS_" nodequeue-operator-=) nodequeue (this :pointer)
                                                                      (arg1 nodequeue))

(cffi:defcfun ("_ZN9nodequeueC1ERKS_" nodequeue-constructor) :void (this :pointer) (arg1 nodequeue))

(cl:defun nodequeue-new ()
  (cl:let ((instance (cffi:foreign-alloc 'nodequeue)))
    (nodequeue-constructor instance)
    instance))

(cffi:defcfun ("_ZN9nodequeueC1Ev" nodequeue-constructor) :void (this :pointer))

(cl:defun nodequeue-new ()
  (cl:let ((instance (cffi:foreign-alloc 'nodequeue)))
    (nodequeue-constructor instance)
    instance))

(cffi:defcfun ("_ZN11textlabel_taSERKS_" textlabel-t-operator-=) textlabel-t (this :pointer)
                                                                             (arg1 textlabel-t))

(cffi:defcfun ("_ZN11textlabel_tC1ERKS_" textlabel-t-constructor) :void (this :pointer)
                                                                        (arg1 textlabel-t))

(cl:defun textlabel-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'textlabel-t)))
    (textlabel-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN11textlabel_tC1Ev" textlabel-t-constructor) :void (this :pointer))

(cl:defun textlabel-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'textlabel-t)))
    (textlabel-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN12Agraphinfo_taSERKS_" agraphinfo-t-operator-=) agraphinfo-t (this :pointer)
                                                                                (arg1 agraphinfo-t))

(cffi:defcfun ("_ZN12Agraphinfo_tC1ERKS_" agraphinfo-t-constructor) :void (this :pointer)
                                                                          (arg1 agraphinfo-t))

(cl:defun agraphinfo-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agraphinfo-t)))
    (agraphinfo-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN12Agraphinfo_tC1Ev" agraphinfo-t-constructor) :void (this :pointer))

(cl:defun agraphinfo-t-new ()
  (cl:let ((instance (cffi:foreign-alloc 'agraphinfo-t)))
    (agraphinfo-t-constructor instance)
    instance))

(cffi:defcfun ("_ZN3boxaSERKS_" box-operator-=) box (this :pointer) (arg1 box))

(cffi:defcfun ("_ZN15shape_functionsaSERKS_" shape-functions-operator-=) shape-functions (this :pointer)
                                                                                         (arg1 shape-functions))

(cffi:defcfun ("_ZN15shape_functionsC1ERKS_" shape-functions-constructor) :void (this :pointer)
                                                                                (arg1 shape-functions))

(cl:defun shape-functions-new ()
  (cl:let ((instance (cffi:foreign-alloc 'shape-functions)))
    (shape-functions-constructor instance)
    instance))

(cffi:defcfun ("_ZN15shape_functionsC1Ev" shape-functions-constructor) :void (this :pointer))

(cl:defun shape-functions-new ()
  (cl:let ((instance (cffi:foreign-alloc 'shape-functions)))
    (shape-functions-constructor instance)
    instance))

(cffi:defcfun ("_ZN5elistaSERKS_" elist-operator-=) elist (this :pointer) (arg1 elist))

(cffi:defcfun ("_ZN5elistC1ERKS_" elist-constructor) :void (this :pointer) (arg1 elist))

(cl:defun elist-new ()
  (cl:let ((instance (cffi:foreign-alloc 'elist)))
    (elist-constructor instance)
    instance))

(cffi:defcfun ("_ZN5elistC1Ev" elist-constructor) :void (this :pointer))

(cl:defun elist-new ()
  (cl:let ((instance (cffi:foreign-alloc 'elist)))
    (elist-constructor instance)
    instance))

(cffi:defcstruct _-postscript-alias
  (name (:pointer :char))
  (family (:pointer :char))
  (weight (:pointer :char))
  (stretch (:pointer :char))
  (style (:pointer :char))
  (xfig-code :int)
  (svg-font-family (:pointer :char))
  (svg-font-weight (:pointer :char))
  (svg-font-style (:pointer :char)))

(cffi::defctype postscript-alias _-postscript-alias)

(cffi:defcstruct htmlfont-t
  (name (:pointer :char))
  (color (:pointer :char))
  ;;; Skipping field #<FIELD flags> in #<STRUCT
  ;                                       htmlfont_t> because it has a bitfield type which is not yet supported by CFFI! Check the layout manually!

  ;;; Encountered a field while the previous bitfield typed fields do not add up to 32 or 64 bits. The fields offsets will be wrong in #<STRUCT
  ;                                                                                                                                       htmlfont_t>!
  (flags :char) ; a try to handle bitfield (int flags:7;). not tested
  (cnt :int)
  (size :double))

|#
